import {PlatformEnum} from '@sekeron/domain';
import {Dimensions, Platform, StyleSheet} from 'react-native';
import Colors from '../../../resources/Colors';

const windowWidth = Dimensions.get('window').width;

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: Colors.secondaryThemeColor},
  subContainer: {marginBottom: 10},
  swiperStyle: {height: 250},
  dotStyle: {
    backgroundColor: Colors.primaryCementColor,
    width: 6,
    height: 6,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    // marginTop: 3,
  },
  eventshostByData: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  eventVerticalSpace: {marginVertical: 6},
  eventsHorizontalSpace: {marginHorizontal: 6},
  activeDotStyle: {
    backgroundColor: Colors.whiteColor,
    width: 13,
    height: 6,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    // marginTop: 3,
  },
  fifthContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  sixthContainer: {
    marginVertical: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  descriptionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 56,
    paddingLeft: 0,
    paddingRight: 18,
    borderRadius: 4,
    alignItems: 'center',
  },
  descriptionSecondContainer: {flexDirection: 'column'},
  headingStyle: {
    fontFamily: 'Comfortaa-Bold',
    color: Colors.nonaryThemeColor,
    fontSize: 16,
  },
  hostTextStyle: {
    FontFamily: 'Comfortaa-Light',
    FontSize: 16,
    marginHorizontal: 2,
    color: Colors.primaryBlueColor,
  },
  normalTextStyle: {
    FontFamily: 'Comfortaa-Light',
    FontSize: 14,
    color: Colors.nonaryThemeColor,
  },
  boldtextStyle: {
    fontFamily: 'Comfortaa-Bold',
    color: Colors.nonaryThemeColor,
    fontSize: 14,
  },
  linkTextStyle: {
    fontFamily: 'Comfortaa-Bold',
    color: Colors.primaryBlueColor,
    fontSize: 14,
  },
  sessionStyle: {
    fontSize: 16,
    color: Colors.whiteColor,
    marginHorizontal: 10,
  },
  sessionSomeTitle: {
    fontSize: 16,
    color: Colors.nonaryThemeColor,
  },
  amountOfEvent: {
    color: Colors.whiteColor,
    alignItems: 'center',
    textAlign: 'center',
    fontFamily: 'Comfortaa-Bold',
    fontSize: 16,
    marginVertical: 4,
  },
  postImageContainer: {
    // flex: 1,
    // position: 'relative',
    height: 250,
    width: windowWidth,
    backgroundColor: Colors.primaryThemeColor,
    marginBottom: 10,
  },
  viewPostText: {color: Colors.whiteColor, fontSize: 12},
  swiperContentContainerStyle: {
    position: 'relative',
    // marginLeft:-20
  },
  paginationStyle: {position: 'absolute', bottom: 12},
  buttonWrapperStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backgroundImage: {
    width: windowWidth,
    height: 270,
    resizeMode: 'cover',
  },
  sessionImages: {
    height: 100,
    width: 200,
    borderRadius: 10,
    marginVertical: 10,
    overflow: 'hidden',
  },
  secondaryContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    height: 40,
    width: 40,
    borderRadius: 25,
    // paddingHorizontal: 20,
    marginTop: Platform.OS === PlatformEnum.ios ? 15 : 5,
    opacity: 0.7,
  },
  contentContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  artistOfTheWeekContainer: {
    position: 'absolute',
    top: 0,
    right: 20,
  },
  eventIconContainer: {
    position: 'absolute',
    top: 10,
    left: 0,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    paddingHorizontal: 10,
  },
  bellIcon: {
    resizeMode: 'contain',
    width: 20,
    height: 20,
  },
  hostedBy: {
    color: Colors.primaryBlueColor,
    fontFamily: 'Comfortaa-Light',
    fontSize: 12,
  },
  hostDays: {
    color: Colors.secondaryGreyColor,
    marginHorizontal: 6,
    fontSize: 12,
  },
  divider: {
    borderColor: Colors.blackColorShade,
    borderWidth: 0.3,
  },
  fouthContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  photoWalkContainer: {
    backgroundColor: Colors.whiteColor,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderRadius: 8,
    overflow: 'hidden',
    marginVertical: 4,
  },
  eventPhotoWalkText: {
    color: Colors.primaryThemeColor,
    padding: 2,
    textAlign: 'center',
    alignItem: 'center',
    fontSize: 12,
    fontFamily: 'Comfortaa-Bold',
    margin: 1,
    paddingHorizontal: 4,
  },
  postCaption: {
    color: Colors.whiteColor,
    marginTop: 5,
  },
  captionContainer: {
    marginHorizontal: 15,
  },
  semiContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    //   justifyContent: 'space-between',
  },
  imageStyles: {width: '100%', height: '100%'},
  semiSubContainer: {width: 15, height: 15, marginHorizontal: 4},
  imageContainer: {width: 15, height: 15, marginHorizontal: 4},
  notifierTimeAgo: {
    color: Colors.nonaryThemeColor,
    fontFamily: 'Comfortaa-Bold',
    fontSize: 12,
  },
  attendContainer: {
    backgroundColor: Colors.darkBlueMagentaColor,
    padding: 10,
    marginVertical: 10,
  },
  successFullyAppiledButtomstyle: {
    flexDirection: 'row',
    alignItems: 'center',
    width: windowWidth,
    margin: 12,
  },
  successFullyImage: {width: 40, height: 40},
  successFullyText: {
    color: Colors.whiteColor,
    fontSize: 16,
    FontFamily: 'Comfortaa-Light',
  },
  freeApplyOverLay: {
    bottom: 0,
    position: 'absolute',
    backgroundColor: Colors.darkBlueMagentaColor,
  },
});
