export const BestOfEventsJson = [
  {
    profileName: 'Stacey Kibbler',
    id: 1,
    isLiked: false,
    isSaved: false,
    isFollowed: true,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'PAID',
    questionType:true,
    attachments: [
      {
        post: 'https://picsum.photos/1200',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1300',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1400',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1500',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1600',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1700',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1800',
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Spring Poster Design Contest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 2,
    isLiked: false,
    isSaved: false,
    isFollowed: true,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'FREE',
    attachments: [
      {
        post: 'https://picsum.photos/2300',
        height: 250,
        width: 183,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1900',
        likes: 734,
        isLiked: true,
        height: 250,
        width: 183,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 3,
    isLiked: true,
    isSaved: true,
    isFollowed: false,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'FREE',
    attachments: [
      {
        post: 'https://picsum.photos/1800',
        likes: 875,
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 4,
    isLiked: false,
    isFollowed: false,
    isSaved: false,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'PAID',
    questionType:false,
    attachments: [
      {
        post: 'https://picsum.photos/2500',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://images.pexels.com/photos/12139674/pexels-photo-12139674.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
];

export const workshopJson = [
  {
    profileName: 'Stacey Kibbler',
    id: 1,
    isLiked: false,
    isSaved: false,
    isFollowed: true,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'PAID',
    questionType:true,
    attachments: [
      {
        post: 'https://picsum.photos/1200',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1300',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1400',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1500',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1600',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1700',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1800',
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Spring Poster Design Contest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 2,
    isLiked: false,
    isSaved: false,
    isFollowed: true,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'FREE',
    attachments: [
      {
        post: 'https://picsum.photos/2300',
        height: 250,
        width: 183,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1900',
        likes: 734,
        isLiked: true,
        height: 250,
        width: 183,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 3,
    isLiked: true,
    isSaved: true,
    isFollowed: false,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'FREE',
    attachments: [
      {
        post: 'https://picsum.photos/1800',
        likes: 875,
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 4,
    isLiked: false,
    isFollowed: false,
    isSaved: false,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'PAID',
    questionType:false,
    attachments: [
      {
        post: 'https://picsum.photos/2500',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://images.pexels.com/photos/12139674/pexels-photo-12139674.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
];

export const competitionJson = [
  {
    profileName: 'Stacey Kibbler',
    id: 1,
    isLiked: false,
    isSaved: false,
    isFollowed: true,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'PAID',
    questionType:true,
    attachments: [
      {
        post: 'https://picsum.photos/1200',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1300',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1400',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1500',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1600',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1700',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1800',
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Spring Poster Design Contest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 2,
    isLiked: false,
    isSaved: false,
    isFollowed: true,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'FREE',
    attachments: [
      {
        post: 'https://picsum.photos/2300',
        height: 250,
        width: 183,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1900',
        likes: 734,
        isLiked: true,
        height: 250,
        width: 183,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 3,
    isLiked: true,
    isSaved: true,
    isFollowed: false,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'FREE',
    attachments: [
      {
        post: 'https://picsum.photos/1800',
        likes: 875,
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  
];

export const eventsQuestions = [
  {
    id: '1',
    question: 'Do you have a laptop?',
    isSelected: false,
  },
  {
    id: '2',
    question: 'Do you have a pendrive?',
    isSelected: false,
  },
  {
    id: '3',
    question: 'Are you ok with making calls ?',
    isSelected: false,
  },
  {
    id: '4',
    question: 'Do you line a mumbai?',
    isSelected: false,
  },
  {
    id: '5',
    question: 'Do you have  a guitar?',
    isSelected: false,
  },
];

export const MoreEventsJson = [
  {
    profileName: 'Stacey Kibbler',
    id: 1,
    isLiked: false,
    isSaved: false,
    isFollowed: true,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'PAID',
    questionType:true,
    attachments: [
      {
        post: 'https://picsum.photos/1200',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1300',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1400',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1500',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1600',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1700',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1800',
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Spring Poster Design Contest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 2,
    isLiked: false,
    isSaved: false,
    isFollowed: true,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'FREE',
    attachments: [
      {
        post: 'https://picsum.photos/2300',
        height: 250,
        width: 183,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1900',
        likes: 734,
        isLiked: true,
        height: 250,
        width: 183,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 3,
    isLiked: true,
    isSaved: true,
    isFollowed: false,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'FREE',
    attachments: [
      {
        post: 'https://picsum.photos/1800',
        likes: 875,
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 4,
    isLiked: false,
    isFollowed: false,
    isSaved: false,
    profileImage: 'https://picsum.photos/300',
    eventType: 'PAID',
    questionType:true,
    attachments: [
      {
        post: 'https://picsum.photos/2500',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://images.pexels.com/photos/12139674/pexels-photo-12139674.jpeg?auto=compress&cs=tinysrgb&w=800&lazy=load',
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 5,
    isLiked: false,
    isFollowed: false,
    isSaved: false,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'PAID',
    questionType:true,
    attachments: [
      {
        post: 'https://picsum.photos/700',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/200',
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
  {
    profileName: 'Stacey Kibbler',
    id: 6,
    isLiked: false,
    isFollowed: false,
    isSaved: false,
    profileImage: 'https://picsum.photos/2600',
    eventType: 'PAID',
    questionType:false,
    attachments: [
      {
        post: 'https://picsum.photos/1500',
        height: 250,
        width: 390,
        type: 'image',
      },
      {
        post: 'https://picsum.photos/1900',
        height: 250,
        width: 390,
        type: 'image',
      },
    ],
    caption: 'Music fest',
    hostedBy: 'Hosted by Sekeron',
    days: '3d',
    admirations: '32 Admirations',
    comments: 'View all 10 Comments',
    dateAndTimeOfEvent: '8PM, 12th June - 9AM 14th August',
    locationOfEvent: 'Jaynagar, Bengaluru',
  },
];
