export const EventProfileJson = [
  {
    id: 1,
    eventImage: 'https://picsum.photos/1000',
    eventTitle: 'Spring Poster Design Contest',
    hostedBy: 'Hosted by Sekeron',
    dateAndTimeOfEvent: '7PM, 12th June - 9AM 14th August ',
    locationOfEvent: 'Jaynagar, Bengaluru',
    status: 'Ongoing',
  },
  {
    id: 2,
    eventImage: 'https://picsum.photos/100',
    eventTitle: 'Spring Poster Design Contest',
    hostedBy: 'Hosted by Sekeron',
    dateAndTimeOfEvent: '7PM, 12th June - 9AM 14th August ',
    locationOfEvent: 'Jaynagar, Bengaluru',
    status: 'Completed',
  },
  {
    id: 3,
    eventImage: 'https://picsum.photos/600',
    eventTitle: 'Spring Poster Design Contest',
    hostedBy: 'Hosted by Sekeron',
    dateAndTimeOfEvent: '7PM, 12th June - 9AM 14th August ',
    locationOfEvent: 'Jaynagar, Bengaluru',
    status: 'Completed',
  },
  {
    id: 4,
    eventImage: 'https://picsum.photos/200',
    eventTitle: 'Spring Poster Design Contest',
    hostedBy: 'Hosted by Sekeron',
    dateAndTimeOfEvent: '7PM, 12th June - 9AM 14th August ',
    locationOfEvent: 'Jaynagar, Bengaluru',
    status: 'Upcoming',
  },
  {
    id: 5,
    eventImage: 'https://picsum.photos/300',
    eventTitle: 'Spring Poster Design Contest',
    hostedBy: 'Hosted by Sekeron',
    dateAndTimeOfEvent: '7PM, 12th June - 9AM 14th August ',
    locationOfEvent: 'Jaynagar, Bengaluru',
    status: 'Ongoing',
  },
  {
    id: 6,
    eventImage: 'https://picsum.photos/400',
    eventTitle: 'Spring Poster Design Contest',
    hostedBy: 'Hosted by Sekeron',
    dateAndTimeOfEvent: '7PM, 12th June - 9AM 14th August ',
    locationOfEvent: 'Jaynagar, Bengaluru',
    status: 'Upcoming',
  },
];
