import {StyleSheet} from 'react-native';
import Colors from '../../resources/Colors';

const styles = StyleSheet.create({
  container: {
    height: 8,
    width: 275,
    backgroundColor: Colors.primaryThemeColor,
    overflow: 'hidden',
    position: 'relative',
    left: -5,
    bottom: 29,
    zIndex: -99,
    borderBottomLeftRadius: 24,
  },
  progressBar: {
    height: '100%',
    borderBottomColor: Colors.primaryBlueColor,
    borderBottomWidth: 24,
    borderBottomLeftRadius: 48,
    position: 'absolute',
  },
  inputContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    borderBottomColor: Colors.blackColorShade,
    borderBottomWidth: 2,
    marginBottom: 30,
  },
  postTitleStyle: {
    marginTop: 20,
    height: 59,
    width: 305,
    paddingHorizontal: 12,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
    borderColor: Colors.primaryVioletColor,
  },
  postTitleInputStyle: {
    fontSize: 16,
    color: Colors.whiteColor,
    fontFamily: 'Comfortaa-Regular',
  },
  postTitleLabelStyle: {
    fontSize: 14,
    position: 'absolute',
    top: -15,
    left: 10,
    backgroundColor: Colors.primaryThemeColor,
    paddingHorizontal: 4,
    borderColor: Colors.secondaryGreyColor,
    color: Colors.nonaryGreyColor,
    fontFamily: 'Comfortaa-Regular',
  },
  postTitlePlaceholderStyle: {
    fontSize: 16,
    color: Colors.secondaryGreyColor,
    marginLeft: 26,
    fontFamily: 'Comfortaa-Regular',
  },
  postDescriptionStyle: {
    marginTop: 30,
    marginBottom: 20,
    height: 109,
    width: 305,
    paddingHorizontal: 12,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
    borderColor: Colors.primaryVioletColor,
  },
  postDescriptionInputStyle: {
    fontSize: 16,
    color: Colors.whiteColor,
    fontFamily: 'Comfortaa-Regular',
  },
  postDescriptionLabelStyle: {
    fontSize: 14,
    position: 'absolute',
    top: -15,
    left: 10,
    backgroundColor: Colors.primaryThemeColor,
    paddingHorizontal: 4,
    borderColor: Colors.secondaryGreyColor,
    color: Colors.nonaryGreyColor,
    fontFamily: 'Comfortaa-Regular',
  },
  postDescriptionPlaceholderStyle: {
    fontSize: 16,
    color: Colors.secondaryGreyColor,
    marginLeft: 26,
    fontFamily: 'Comfortaa-Regular',
  },
  backgroundColorContainer: {
    backgroundColor: Colors.senaryGreyColor,
    paddingVertical: 15,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backgroundColorIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: Colors.purplecolorShade,
    borderWidth: 2,
    borderColor: Colors.whiteColor,
    marginHorizontal: 15,
  },
  selectBackgroundText: {
    color: Colors.nonaryGreyColor,
    fontSize: 14,
    fontFamily: 'Comfortaa-Light',
  },
  colorPickerContainer: {
    position: 'absolute',
    width: 300,
    height: 400,
    right: 25,
    top: '15%',
    zIndex: 999,
  },
});

export default styles;
