const strings = {
  // Input Labels
  enterEmailId: 'Enter Email/User name',
  enterFullName: 'Enter your full name',
  selectGender: 'Select your gender',
  enterPhoneNumber: 'Enter your Phone number',
  enterUserName: 'Enter your username',
  selectRole: 'Select/Enter your role',
  enterDateOfBirth: 'Enter your date of birth',
  enterEmailOrUserName: 'Email/Mobile/User name',
  countryCode: '+91',
  selectWhatAmusesYou: 'Select what amuses you!',
  postTitle: 'Post title (Optional)',
  descrption: 'Description (Optional)',
  projectName: 'Project name',
  projectCategory: 'Project category',
  ownerShipType: 'Ownership type',
  revenueShareType: 'Revenue Share Type',
  startDate: 'Start Date',
  endDate: 'End Date',
  enterAddressManually: 'Enter full address manually',
  share: 'Share %',
  fullName: 'fullName',
  gender: 'gender',
  phoneNumber: 'phoneNumber',
  dateOfBirth: 'dateOfBirth',
  userName: 'userName',
  roles: 'roles',
  address: 'Address (Optional)',
  postDescription: 'Description (Optional)',

  // info
  enterTheCodeSentTo: 'Enter the code sent to',
  thanksOneLastOneStep: 'Thanks! One last step',
  letsPersonalizeYourProfile: 'Lets personalize your profile',
  thatsGreatName: ',thats a great name!',
  greetingsFromSkeron: 'Greetings from Sekeron',
  whatsYourName: 'What’s your name?',
  whenIsYourBirthday: 'When is your birthday?',
  others: 'others',
  createCustomSkill: 'Create Custom Skill',
  login: 'Login',
  letsSetPassword: 'Lets set a password',
  uploadedFilesWillBeShownHere: 'Uploaded files will be shown here',
  createPost: 'Create post',
  dragAndDrop: 'Drag & Drop Files here',
  createAPost: 'Create a post',
  uploadYourDesires: 'Upload your desired media using the tools below',
  previewPost: 'Preview Post',
  publishPost: 'Publish Post',
  backToEditPost: 'Back to edit Post',
  mediaGallery: 'Media Gallery',
  description: 'Description',
  sendCode: ' Send Code to ',
  reply: 'Reply',
  hideReplies: 'Hide Replies',
  replies: 'Replies',
  comments: 'Comments',
  post: 'Post',
  addAComment: 'Add a Comment',
  reorderingContents: 'Reordering contents',
  selectColor: 'Select background colour of your post',
  publishPostSuccessMessage: 'Your Post has been published successfully.',
  cancelPostCreation: 'Cancel Post creation?',
  youMightLoseChanges: 'You might lose any changes you’ve made on this page.',
  deleteItem: 'Delete Item?',
  discardChanges: 'Discard Changes ?',
  delete: 'Delete',
  cancel: 'Cancel',
  stay: 'Stay',
  slideToCancel: 'Slide to cancel',
  tapHoldToRecord: 'Tap and hold to record',
  holdToRecordReleaseToStop: 'Hold to record, Release to stop',
  recording: 'Recording',
  reorderMedia: 'Re-Order Media',
  projectId: 'Project ID:',
  projectAddressInfo:
    'If your project is happening both online and offline, select both the options',
  requiredArtist: 'Required artist',
  collaboratorDisclaimer:
    'Disclaimer: If you have different requirements from the same kind of skill, you can add a separate skill of the same name and add separate requirements in that.',
  addArtistWarningMessage:
    'If you dont add anyone, then the space will be open for people in sekeron platform to apply',
  collaborationTerms: 'Collaboration Terms',
  projectCreationChecklist: 'Project Creation Checklist !',
  termsAndConditionsInfo:
    'Please go through all the documents thoroughly before agreeing',
  agreeToTermsAndConditions: 'I agree to all of the above documents',
  artistType: 'Artist Type',
  projectType: 'Project Type:',
  chooseCoverImage: 'Choose project cover image',
  youmightLooseChanges: 'You might lose any changes you’ve made on this page.',
  projectPublishedSuccefully: 'Your Project has been published successfully.',
  thisWillSendInvitesToAllArtists:
    'This will send Invites to all the added artists?',
  areYouSureYouWantToClearTheSelectedItems:
    'Are you sure you want to clear the selected media?',
  areYouSureYouWantToDiscardChanges: 'Are you sure?',
  sendCodeTo: "Send code to",

  // Success Meassges
  successfulllyVerified: 'WOOHOO!  You have succesfully verified the account',
  letsGetStarted: 'Hey! Lets get you started',
  userNameAvailable: 'This User Name is available',

  // Links
  edit: ' Edit',
  loginHere: ' LOGIN HERE',
  joinedAlready: 'Joined Already?',
  resendOtpIn: 'RESEND OTP in',
  resendOtp: 'RESEND OTP',
  or: 'or',

  // Button text
  continue: 'Continue',
  verify: 'Verify',
  takeMeToHome: 'Take me to my Home',
  donHaveAnAccount: 'Dont have an account?',
  signUpHere: 'SIGN UP HERE',
  sendOtp: 'Send OTP',
  uploadFiles: 'Upload Files',
  getStarted: 'Lets get started',
  uploadFile: 'Upload File',
  clearAll: 'Clear All',
  next: 'Next',
  addMoreMedia: 'Add More Media',
  done: 'Done',
  save: 'Save',
  reorder: 'Reorder',
  addNewCanvas: 'Add a new text canvas',
  enterLocation: 'Enter location on map',
  createProject: 'Create a project',
  addTerm: 'Add term',
  startProjectCreation: 'Start Project Creation',
  previewProjectNow: 'Preview Project Now',
  cancelProjectCreation: 'Cancel Project creation?',
  no: 'No',
  yes: 'Yes',
  publishProject: 'Publish Project',
  backToEditProject: 'Back to edit project',
  discard: 'Discard',

  //errors
  enterValidEmail: 'Please enter a valid email',
  pleaseEnterEmail: 'Please enter an email',
  enterValidFullname: "Full name shouldn't contain a number",
  pleaseEnterFullname: 'Please enter an fullname',
  pleaseSelectGener: 'Please select an gender',
  enterValidPhoneNumber: 'Please enter a valid phone number',
  pleaseEnterPhoneNumber: 'Please enter an phone number',
  pleaseSelectDateofBirth: 'Please select an date of birth',
  pleaseEnterUsername: 'Please enter an username',
  userNameAlreadyExist: 'This user name already exist',
  pleaseSelectRole: 'Please select an role',
  numberOfRolesError: 'Number of roles must be less then 7',
  numberOfCharactersError: 'Minimum 3 characters should be there',
  emailSpacingError: 'Email cannot include leading and trailing spaces',
  dateSelectionError: 'Please select the date',
  onlySixSkillsAdded: 'Only Six skills can be added.',
  permissionsDenied: 'Permissions Denied!',
  enterProjectName: 'please enter project name',
  enterCategory: 'please enter category of the project',
  selectOwnershipType: 'please select ownership type',
  selectRevenueShareType: 'please select revenue share type',
  selectStartDateOftheProject: 'please select start date',

  //Mobile
  ios: 'ios',
  padding: 'padding',
  spinner: 'spinner',
  default: 'default',

  //home
  follow: 'Follow',
  more: '...more',
  admire: 'Admire',
  comment: 'Comment',
  viewPost: 'View Post',
  showLessPosts: 'Show less posts like this',
  showMorePosts: 'Show more posts like this',
  undo: 'Undo',
  trendingProjects: 'Trending Projects',
  upcomingEvents: 'Upcoming Events',
  seeAll: 'SEE ALL',
  registerNow: 'Register now!!',
  postName: 'Trip to the middle of nowhere',
  less: 'less',
  reportPost: 'Report Post',
  shareOutsideSekeron: 'Share outside Sekeron',
  unfollow: 'Unfollow',
  sent: 'Sent',
  send: 'Send',
  following: 'Following',
  artistOfTheWeek: 'Artist of the week',
  writeMessage: 'Write a message...',
  addedToFavourite: 'Added to favourite',
  removedFromFavourite: 'Removed from favourite',
  addCommnet: 'Add a comment...',
  showMorePostsLikeThis: 'Show more posts like this',
  showLessPostsLikeThis: 'Show Less posts like this',

  // Posts
  textOptions: 'Text options',
  newPost: 'New Post',
  addNewTextCanvas: '+ Add a new text canvas',
  new: 'new',
  old: 'old',
  admirations: 'Admirations',

  //Project
  newProject: 'New Project',

  // Profile
  camera: 'Camera',
  gallery: 'Gallery',
  remove: 'Remove',

  readLess: 'Read less',
  readMore: 'Read more',
  saveChanges: 'Save Changes',

  upcoming: 'Upcoming',
  completed: 'Completed',
  ongoing: 'Ongoing',

  // Blogs
  readNow: 'Read now',
  similarBlogs: 'Similar Blogs',
  viewAll: 'View All',
  online: 'ONLINE',
  attend: 'Attend',
  moreLikeThis: 'More Like this',
  applyFilters: 'Apply Filters',
  youHaveAppliedForThisEvent: 'You have applied for this event on ',
  payAnd: 'Pay & ',
  areYoueighteenAndAbove: 'Are you 18 and above?.',
  eventsQuestion: 'Few questions to set you up for the event',
  join: 'join',
  makePaymentOf: 'Make payment of Rs. ',
  doYouHaveLaptop: 'Do you have a laptop?',
  doYouHavePendrie: 'Do you have  a pendrive?',
  areYouOkWithMakingPhoneCalls: 'Are you ok with making calls ?',
  DoyouLiveInMumbai: 'Are you ok with making calls ?',
  doYouHaveGuitar: 'Do you have a guitar?',

  // Notifications

  notifications: 'Notifications',
  Explore: 'Explore',
  postNotificationMessage:
    'Your post related notifications will appear here, create your first post or explore now!',
  projectNotificationMessage:
    'Your project related notifications will appear here, create your first project or explore and collaborate now!',
  eventNotificationMessage:
    'Your events related notifications will appear here, create your first project or explore and collaborate now!',

  // explore

  topProjects: 'Top Projects',
  topEvents: 'Top Events',
  topBlogs: 'Top Blogs',
  topPosts: 'Top Posts',
  featuredArtists: 'Featured Artists',

  // events
  upComingEvents: 'Upcoming Events',

  // dashboard
  myDashboard: 'My Dashboard',
  myProjects: 'My Projects',
  myEvents: 'My Events',
  myCollaborations: 'My Collaborations',
  myCalender: 'My Calender',
  photos: 'Photos',
  videos: 'Videos',
  scripts: 'Scripts',
  audios: 'Audios',
  clearPage: 'Clear Page',
  deletePage: 'Delete Page',
  sendImageToGroup: 'Send image to group',
  switchToDarkMode: 'Switch to dark mode',
  switchToLightMode: 'Switch to light mode',
  collaboratorSettings: 'Collaborator Settings',
  // search
  filterBy: 'filter by',
}

export default strings
