const MediaAssets = {
  ic_successcheckmark: require('./media/ic_successcheckmark/ic_successcheckmark.png'),
  ic_right_arrow: require('./media/ic_right_arrow/ic_right_arrow.png'),
  ic_left_arrow: require('./media/ic_left_arrow/ic_left_arrow.png'),
  ic_star: require('./media/ic_star/ic_star.png'),
  ic_play: require('./media/ic_play/ic_play.png'),
  ic_steppertickmark: require('./media/ic_steppertickmark/ic_steppertickmark.png'),
  ic_calender: require('./media/ic_calender/ic_calender.png'),
  ic_dropdown: require('./media/ic_dropdown/ic_dropdown.png'),
  ic_delete: require('./media/ic_delete/ic_delete.png'),
  ic_caution: require('./media/ic_caution/ic_caution.png'),
  ic_scrollmodel: require('./media/ic_scrollmodel/ic_scrollmodel.png'),
  ic_selectcard: require('./media/ic_selectcard/ic_selectcard.png'),
  ic_fb: require('./media/ic_fb/f_1.png'),
  ic_google: require('./media/ic_google/google.png'),
  ic_more: require('./media/ic_more/more.png'),
  ic_pencilmark: require('./media/ic_pencilmark/pencil.png'),
  ic_carousalpic1: require('./media/ic_carousalpic/carousal1.png'),
  ic_carousalpic2: require('./media/ic_carousalpic/carousal2.png'),
  ic_sekeron: require('./media/ic_sekeron/ic_sekeron.png'),
  ic_errormark: require('./media/ic_errormark/shape.png'),
  ic_apple: require('./media/ic_apple/ic_apple.png'),
  ic_post_notification: require('./media/ic_post_notification/ic_post_notification.png'),
  ic_project_notification: require('./media/ic_project_notification/ic_project_notification.png'),
  ic_event_notification: require('./media/ic_event_notification/ic_event_notification.png'),
  ic_home_active: require('./media/ic_home_active/ic_home_active.png'),
  ic_home_inactive: require('./media/ic_home_inactive/ic_home_inactive.png'),
  ic_add_active: require('./media/ic_add_active/ic_add_active.png'),
  ic_add_inactive: require('./media/ic_add_inactive/ic_add_inactive.png'),
  ic_dashboard_inactive: require('./media/ic_dashboard_inactive/ic_dashboard_inactive.png'),
  ic_dashboard_active: require('./media/ic_dashboard_active/ic_dashboard_active.png'),
  ic_search_inactive: require('./media/ic_search_inactive/ic_search_inactive.png'),
  ic_search_active: require('./media/ic_search_active/ic_search_active.png'),
  ic_profile_inactive: require('./media/ic_profile_inactive/ic_profile_inactive.png'),
  ic_profile_active: require('./media/ic_profile_active/ic_profile_active.png'),
  ic_notification: require('./media/ic_notification/ic_notification.png'),
  ic_message: require('./media/ic_message/ic_message.png'),
  ic_admirations_inactive: require('./media/ic_admirations_inactive/ic_admirations_inactive.png'),
  ic_admirations_active: require('./media/ic_admirations_active/ic_admirations_active.png'),
  ic_more_options: require('./media/ic_more_options/ic_more_options.png'),
  ic_comments: require('./media/ic_comments/ic_comments.png'),
  ic_save: require('./media/ic_save/ic_save.png'),
  ic_share: require('./media/ic_share/ic_share.png'),
  ic_mute: require('./media/ic_volume/ic_volume.png'),
  ic_pause: require('./media/ic_pause/ic_pause.png'),
  ic_header_back_arrow: require('./media/ic_header_back_arrow/ic_header_back_arrow.png'),
  profile_pic: require('./media/profile-pic.jpg'),
  ic_unmute: require('./media/ic_mute/ic_mute.png'),
  ic_video_play: require('./media/ic_video_play/ic_video_play.png'),
  ic_save_active: require('./media/ic_save_active/ic_save_active.png'),
  ic_succesfully_applied_icon: require('./media/ic_succesfully_applied/ic_succesfully_applied.png'),
  ic_create_new_postIcon: require('./media/ic_create_new_post/ic_create_new_post.png'),
  ic_create_new_projectIcon: require('./media/ic_create_new_project/ic_create_new_project.png'),
  ic_add_photo: require('./media/ic_add_photo/ic_add_photo.png'),
  ic_combined_shape: require('./media/ic_combined_shape/ic_combined_shape.png'),
  ic_audio_post_not_selected: require('./media/ic_audio_post_not_selected/ic_audio_post_not_selected.png'),
  ic_video_post_not_selected: require('./media/ic_video_post_not_selected/ic_video_post_not_selected.png'),
  ic_text_post_not_selected: require('./media/ic_text_post_not_selected/ic_text_post_not_selected.png'),
  ic_audio_post: require('./media/ic_audio_post/ic_audio_post.png'),
  ic_drag: require('./media/ic_drag/ic_drag.png'),
  ic_red_cross: require('./media/ic_red_cross/ic_red_cross.png'),
  ic_text_post: require('./media/ic_text_post/ic_text_post.png'),
  ic_video_post: require('./media/ic_video_post/ic_video_post.png'),
  ic_add_photo_not_selected: require('./media/ic_add_photo_not_selected/ic_add_photo_not_selected.png'),
  ic_diamond_shape: require('./media/ic_diamond_shape/ic_diamond_shape.png'),
  ic_recorder_icon: require('./media/ic_recorder_icon/ic_recorder_icon.png'),
  ic_recording_icon: require('./media/ic_recording_icon/ic_recording_icon.png'),
  ic_red_delete_icon: require('./media/ic_red_delete_icon/ic_red_delete_icon.png'),
  ic_recorded_upload: require('./media/ic_recorded_upload/ic_recorded_upload.png'),
  ic_grey_left_arrow: require('./media/ic_grey_left_arrow/ic_grey_left_arrow.png'),
  ic_lock: require('./media/ic_lock/ic_lock.png'),
  ic_arrow_up: require('./media/ic_arrow_up/ic_arrow_up.png'),
  ic_mic_big: require('./media/ic_mic_big/ic_mic_big.png'),
  ic_white_mic: require('./media/ic_white_mic/ic_white_mic.png'),
  ic_stop_recording: require('./media/ic_stop_recording/ic_stop_recording.png'),
  ic_status_on_going_icon: require('./media/ic_status_on_going_icon/ic_status_on_going_icon.png'),
  ic_status_complete_icon: require('./media/ic_status_complete_icon/ic_status_complete_icon.png'),
  ic_calander_open_icon: require('./media/ic_calander_open_icon/ic_calander_open_icon.png'),
  ic_status_up_coming_icon: require('./media/ic_status_up_coming_icon/ic_status_up_coming_icon.png'),
  ic_location_icon: require('./media/ic_location_icon/ic_location_icon.png'),
  ic_graduation_cap_icon: require('./media/ic_graduation_cap_icon/ic_graduation_cap_icon.png'),
  ic_suitcase_icon: require('./media/ic_suitcase_icon/ic_suitcase_icon.png'),
  ic_city_icon: require('./media/ic_city_icon/ic_city_icon.png'),
  ic_flag_icon: require('./media/ic_flag_icon/ic_flag_icon.png'),
  ic_instagram_icon: require('./media/ic_instagram_icon/ic_instagram_icon.png'),
  ic_facebook_icon: require('./media/ic_facebook_icon/ic_facebook_icon.png'),
  ic_pinterest_circular_icon: require('./media/ic_pinterest_circular_icon/ic_pinterest_circular_icon.png'),
  ic_youtube_icon: require('./media/ic_youtube_icon/ic_youtube_icon.png'),
  ic_image_cancel_icon: require('./media/ic_image_cancel_icon/ic_image_cancel_icon.png'),
  ic_gallery_icon: require('./media/ic_gallery_icon/ic_gallery_icon.png'),
  ic_camera_icon: require('./media/ic_camera_icon/ic_camera_icon.png'),
  ic_grey_dropdown_icon: require('./media/ic_grey_dropdown_icon/ic_grey_dropdown_icon.png'),
  ic_edit_pencil_icon: require('./media/ic_edit_pencil_icon/ic_edit_pencil_icon.png'),
  ic_profile_default_cover_image:require('./media/ic_profile_default_cover_image/ic_profile_default_cover_image.png'),
  ic_profile_default_avator:require('./media/ic_profile_default_avator/ic_profile_default_avator.png'),
  ic_left_align: require('./media/ic_left_align/ic_left_align.png'),
  ic_right_align: require('./media/ic_right_align/ic_right_align.png'),
  ic_center_align: require('./media/ic_center_align/ic_center_align.png'),
  ic_bold: require('./media/ic_bold/ic_bold.png'),
  ic_italic: require('./media/ic_italic/ic_italic.png'),
  ic_underline: require('./media/ic_underline/ic_underline.png'),
  ic_undo: require('./media/ic_undo/ic_undo.png'),
  ic_redo: require('./media/ic_redo/ic_redo.png'),
  ic_color_picker: require('./media/ic_color_picker/ic_color_picker.png'),
  ic_red_bell_icon:require('./media/ic_red_bell_icon/ic_red_bell_icon.png'),
  ic_gery_bell_icon:require('./media/ic_grey_bell_icon/ic_grey_bell_icon.png'),
  ic_filter_icon:require('./media/ic_filter_icon/ic_filter_icon.png'),
  ic_checkbox_checked:require('./media/ic_checkbox_checked/ic_checkbox_checked.png'),
  ic_checkbox_unchecked:require('./media/ic_checkbox_unchecked/ic_checkbox_unchecked.png'),
  ic_oval_unchecked_icon:require('./media/ic_oval_unchecked_icon/ic_oval_unchecked_icon.png'),
  ic_oval_checked_icon:require('./media/ic_oval_checked_icon/ic_oval_checked_icon.png'),
  ic_icon_close:require('./media/ic_icon_close/ic_icon_close.png'),
  ic_right_arrow_icon:require('./media/ic_right_arrow_icon/ic_right_arrow_icon.png'),
  ic_up_arrow_icon:require('./media/ic_up_arrow_icon/ic_up_arrow_icon.png'),
  ic_more_option_black_icon:require('./media/ic_more_option_black_icon/ic_more_option_black_icon.png'),
};

export default MediaAssets;
