import {StyleSheet} from 'react-native';
import Colors from '../../../../resources/Colors';

const createProfileStyles = StyleSheet.create({
  container: {flex: 1, justifyContent: 'center'},
  secondaryContainer: {alignItems: 'center'},
  oneLastStepText: {
    fontSize: 15,
    textAlign: 'center',
    color: Colors.nonaryThemeColor,
    marginTop: 30,
  },
  personaliseYourProfileText: {
    fontSize: 24,
    textAlign: 'center',
    color: Colors.secondaryGreyColor,
    marginTop: 40,
    fontFamily: 'Comfortaa-Regular',
  },
  placeHolder: {
    height: 59,
    paddingHorizontal: 12,
    borderRadius: 24,
    borderWidth: 1,
    fontFamily: 'Comfortaa-Regular',
  },
  input: {
    placeholderTextColor: Colors.secondaryGreyColor,
    color: Colors.secondaryGreyColor,
    fontFamily: 'Comfortaa-Regular',
  },
  inValidInput: {
    borderColor: Colors.reddishPinkColor,
    fontFamily: 'Comfortaa-Regular',
  },
  validInput: {
    borderColor: Colors.primaryBlueColor,
    fontFamily: 'Comfortaa-Regular',
  },
  inputStyle: {
    fontSize: 16,
    color: Colors.whiteColor,
    marginLeft: 10,
    fontFamily: 'Comfortaa-Regular',
  },
  labelStyle: {
    fontSize: 14,
    position: 'absolute',
    top: -10,
    backgroundColor: Colors.primaryThemeColor,
    paddingHorizontal: 4,
    borderColor: Colors.secondaryGreyColor,
    color: Colors.secondaryGreyColor,
    fontFamily: 'Comfortaa-Regular',
  },
  placeholderStyle: {
    fontSize: 16,
    color: Colors.secondaryGreyColor,
    marginLeft: 10,
    fontFamily: 'Comfortaa-Regular',
  },
  textErrorStyle: {
    fontSize: 16,
    fontFamily: 'Comfortaa-Regular',
  },
  inputContainer: {
    marginTop: 25,
    zIndex: 2,
    fontFamily: 'Comfortaa-Regular',
  },
  placeHolderWidth: {
    width: 305,
    fontFamily: 'Comfortaa-Regular',
  },
  skillTagsHolder: {
    justifyContent: 'space-around',
    borderRadius: 24,
    borderWidth: 1,
    zIndex: 1,
  },
  filledTagInput: {
    paddingVertical: 14,
  },
  emptySkilledTagInput: {
    paddingVertical: 10,
  },
  skillTagsInputHolder: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginLeft: 15,
    marginTop: 10,
    marginBottom: 10,
    justifyContent: 'flex-start',
    marginRight: 10,
  },
  enterYourRoleText: {
    position: 'absolute',
    backgroundColor: Colors.primaryThemeColor,
    left: 60,
    top: 240,
    zIndex: 999,
    paddingHorizontal: 10,
    fontSize: 14,
    color: Colors.nonaryThemeColor,
    fontFamily: 'Comfortaa-Regular',
  },
  skillTags: {
    marginRight: 8,
    marginBottom: 4,
    paddingLeft: 14,
    borderRadius: 12,
    flexDirection: 'row',
    backgroundColor: Colors.primaryBlueColor,
    flexWrap: 'wrap',
    marginTop: 5,
  },
  skills: {
    color: Colors.octonaryGreyColor,
    fontSize: 15,
  },
  skillsInputHolder: {
    flex: 1,
    color: Colors.whiteColor,
    fontSize: 15,
    marginLeft: 5,
    fontFamily: 'Comfortaa-Regular',
  },
  deleteTag: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
    marginLeft: 15,
  },
  skillsHolder: {
    minHeight: 50,
    paddingHorizontal: 8,
    borderRadius: 24,
    alignItems: 'flex-start',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
    backgroundColor: Colors.senaryGreyColor,
    zIndex: 1,
  },
  skillsOptionHolder: {
    minHeight: 50,
  },
  skillOptions: {
    color: Colors.secondaryBlueColor,
    fontSize: 18,
    marginTop: 10,
    marginBottom: 5,
  },
  createCustomSkill: {
    color: Colors.secondaryBlueColor,
    fontSize: 18,
  },
  homeButtonHolder: {marginTop: 50},
  enabledButton: {
    borderRadius: 22,
    justifyContent: 'center',
    margin: 5,
    width: '100%',
    height: 50,
  },
  disabledButton: {
    width: 250,
    height: 50,
    paddingHorizontal: 40,
    backgroundColor: Colors.quaternaryGreyColor,
    borderRadius: 22,
    justifyContent: 'center',
    borderColor: Colors.secondaryGreyColor,
  },
  filledInput: {
    borderColor: Colors.primaryBlueColor,
  },
  emptyInput: {
    borderColor: Colors.secondaryGreyColor,
  },
  errorMsg: {
    marginRight: 5,
    resizeMode: 'contain',
    width: 15,
    height: 15,
  },
  validationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 70,
  },
  validationErrorText: {color: Colors.reddishPinkColor},
  backButton: {height: 25, resizeMode: 'contain', width: 25},
  backButtonContainer: {position: 'absolute', top: '-22%', left: 20},
});
export default createProfileStyles;
