export const routes = {
  createPostModal: 'CreatePostModal',
  createPost: 'CreatePostScreen',
  createPosts: 'CreatePosts',
  projects: 'ProjectsScreen',
  explore: 'ExploreScreen',
  home: 'HomeScreen',
  profile: 'ProfileScreen',
  viewPost: 'ViewPost',
  notifications:'Notifications',
  registration: 'Registration',
  login: 'Login',
  images: 'Images',
  audios: 'Audios',
  videos: 'Videos',
  texts: 'Texts',
  cameraScreen: 'cameraScreen',
  reorder: 'reorder',
  addAdditionalPostDetails: 'addAdditionalPostDetails',
  previewPost: 'PreviewPost',
  editProfile:'Edit Profile',
  favourites:'My Favourites',
  events:'events',
  eventsDetailsPage:'EventsDetailsPage',
  blogs:'Blogs',
  blogsDetails:'BlogsDetails',
  blogsSearch:'blogsSearch'
};

